### PR TITLE
Delete SQL Objects from a bucket

### PR DESCRIPTION
**Pull request by aa7955**
Delete specific SQL query objects from the SQL query bucket. 

@torsstei I think this should also work on Py2. Instead of recreating the XML data, I just used COS SDK because it's all built in.

### CODE REVIEW

**Comment by torsstei** [comment]
Awesome @aa7955 ! The return of  `cos_client.delete_objects()` is apparently not a response object and the check for `response.HTTPStatusCode` afterwards fails. But the delete works fine. I think you can simple remove the check because the ibm_boto3 client is probably checking the status anyway. 

I'd suggest that you print out the list of `bucket_objects` after successful deletion.

**Comment by torsstei** [comment]
@aa7955 I have also invited you to the repository now. So you can do PR branches in there directly.

**Comment by aa7955** [comment]
@torsstei I think I need to write a check in here to test if the objects exist. Currently, if the objects don't exist, then it'll throw an error.

**Comment by aa7955** [comment]
Merged in 0.2.0

**Pull request closed without merging**
